code/API_definitions/qos-stable-latency.yaml, code/API_definitions/qos-throughput.yaml
Correction in security requirements.
=> Issue #9 correction

code/API_definitions/qos-stable-latency.yaml
This pull request is to address #20
=> Qod latency api spec 0.1.0 contribution

code/API_definitions/qos-throughput.yaml
This pull request is to address #20
=> Qod bandwidth api spec 0.1.0 contribution

documentation/API_documentation/QoD_API.md
Updates as suggested in https://github.com/camaraproject/QualityOnDemand/pull/76#pullrequestreview-1234464232
Fixes #78
=> Some more editiorial updates of documentation QoD_API.md

README.md
Harmonization with content on CAMARA Website
=> ShowResultsInReadme

code/API_definitions/qod-api.yaml, documentation/API_documentation/QoD_API.md
Added Generic error 500 to remaining procedures
=> Added Generic error 500 to remaining procedures

documentation/MeetingMinutes/MOM-2023-01-13.md
Minutes from our call on Friday, Januar 13th.
=> Add MOM-2023-01-13

code/API_definitions/qod-api.yaml, documentation/API_documentation/QoD_API.md
This PR is related to #81 and align to PR #104 reformatting errors according to the guidelines.
=> Introducing error code 501 "Not Implemented"

README.md
* Update to latest release
* Fixed links of API definition and documentation
* Added link to previous release v0.8.0 for convenience
=> Fix/Update of README.md to release v0.8.1

README.md
Adapted time zone of meeting schedule to daylight saving time.
=> fix/Update README.md for daylight saving time

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue_bug_template.md, .github/ISSUE_TEMPLATE/issue_correction_template.md, .github/ISSUE_TEMPLATE/issue_documentation_template.md, .github/ISSUE_TEMPLATE/issue_enhancement_template.md, .github/ISSUE_TEMPLATE/issue_pm_template.md, .github/ISSUE_TEMPLATE/issue_tests_template.md, .github/pull_request_template.md
Adds agreed PR and Issue templates to the QualityOnDemand github repository
No associated issue
Templates introduced by [this ](https://github.com/camaraproject/WorkingGroups/pull/174) PR
None
```
release-note
- Add PR and Issue Templates
```
None
=> Upload of issue and PR templates & config

documentation/MeetingMinutes/MOM-2023-05-05.md
Minutes of meeting 2023-05-05
<!-- Automatically closes linked issue when PR is merged.
na
=> MOM-2023-05-05 

documentation/MeetingMinutes/MOM-2023-05-05.md, documentation/MeetingMinutes/MOM-2023-05-19.md
Will add MOM-2023-05-19
Will correct dates within MOM-2023-05-05
n/a
n/a
=> Mom 2023 05 19

MAINTAINERS.MD
* Added Spry Fox Networks to the Maintainers list.
=> Added Spry Fox Networks to Maintainers

documentation/MeetingMinutes/MOM-2023-06-02.md
Minutes of meeting on Friday June 2nd
na
=> MOM 2023-06-02 created

README.md
Update the README.md with the note about the main branch (frequent changes) and the hint to rely only on published releases. As requested in last QoD community call.
n/a
Fixes #
Sentence copied over from the CHANGELOG.md, just adapted the highlighting.
=> Update README.md with note about main branch

documentation/MeetingMinutes/MOM-2023-06-02.md, documentation/MeetingMinutes/MOM-2023-06-16.md
Created minutes of call on Friday, June 16th
n/a
List of participants might be not complete, please add if needed
Corrected also date in previous MoM
=> Created MOM-2023-06-16.md

code/API_definitions/qod-api.yaml
After the pre-release v0.9.0-rc we will continue to fix bugs on the way to the release v0.9.0. So the version is again "work in progress".
na
na
na
=> Reset version number to 0.9.0-wip after pre-release

code/API_definitions/qod-api.yaml
* bug
Fix error in spec
Detected by #171 
n/a
```
Fix incorrect format value
```
n/a
=> Fix: priority integer format to int32

code/API_definitions/qod-api.yaml
* bug
Fixes a typo
n/a
n/a
```
Fixes typo in enum 'NETWORK_TERMINATED'
```
=> Fixed typo

documentation/MeetingMinutes/MOM-2023-06-30.md
Provide short MOM for the the last QoD call.
na
Notes for second half of the call (input from OGW product team) might need to be added
=> MOM-2023-06-30 created

documentation/MeetingMinutes/MOM-2023-07-14.md
=> MOM-2023-07-14

CHANGELOG.md, code/API_definitions/qod-api.yaml
Update of CHANGELOG.md for the release v0.9.0
Update of version number in YAML file to v0.9.0
The merge commit of this PR will be tagged as release v0.9.0 and get HEAD of release-0.9.0 branch ("Release branch").
Will close #184 
Fixes #184
=> Update of CHANGELOG.md for v0.9.0 release

README.md
Subproject Management
Update of README.md to reflect release v0.9.0 as latest.
Fixes #191 
Are you aware of other places which we should update?
na
=> Update README.md with v0.9.0

code/API_definitions/qod-api.yaml
Changed version number in main branch to v0.10.0-wip to indicate that the content of main branch is work in progress (see also README.md)
Fixes #192
=> Update qod-api.yaml /w v0.10.0-wip

documentation/MeetingMinutes/MOM-2023-07-28.md
Created MOM of QoD on July 28th
na
Please edit directly if changes are needed. I might have missed some points.
=> MOM-2023-07-28 created

.github/workflows/swagger-editor-validator.yml
Updates the version of the checkout action.
The version is based on a depricated version of node.
Fixes #213
```
release-note
```
```
docs
```
=> Update Swagger Editor Validator to use checkout v3

documentation/MeetingMinutes/MOM-2023-08-25.md
MOM of QoD call of August 25th
n/a
Sorrry for the late and probably partly incomplete MoM. Feel free to add missing points.
=> Adding MOM 2023-08-25

documentation/MeetingMinutes/MOM-2023-09-08.md
Minutes of QoD Meeting on September, 8th
na
na
=> Minutes of QoD Meeting 2023-09-08

documentation/MeetingMinutes/MOM-2023-09-22.md
Minutes of meeting held on Friday 22nd September
N/A
None
```
release-note
- Add minutes of meeting for Friday 22nd September
```
None
=> Add minutes of meeting for Friday 22nd September

code/Test_definitions/QoD_API_Test.feature, code/Test_definitions/README.md
* subproject management / tests
The default folder for test definitions was added to https://github.com/camaraproject/Template_Lead_Repository
Housekeeping as described in https://github.com/camaraproject/Governance/issues/98 - Creating code/Test_definitions/README.md
'.feature' file currently in https://github.com/camaraproject/QualityOnDemand/blob/main/code/cucumber/src/test/resources/feature/QoD_API_Test.feature was copied to the default folder
Should the /cucumber folder be deleted?
```
The default folder for test definitions was created.
QoD_API_Test.feature was copied from the current /cucumber folder.
```
=> Alignment with changes in https://github.com/camaraproject/Template_Lead_Repository on test definitions

README.md
Changed order of links as proposed in #239, re-added link to v0.8.1, minor edits.
Fixes #239 
N/A
=> Update README.md - bring user friendly links on top

code/API_definitions/qod-api.yaml
* correction
Remove the basepath and move this to the "url"-property.
Fixes #251
=> feat: move "basePath" /qod/v0 to "url"-property

CHANGELOG.md
* correction
Minor fix after rc2 release within changelog.
=> Update CHANGELOG.md - adding missing full changelog line

CHANGELOG.md, README.md, code/API_definitions/qod-api.yaml
This PR will create the release v0.10.0 of the QualityOnDemand repository:
- Update CHANGELOG.md (with a sum of changes of RC1+2)
- Update README.md
- Change version number in YAML to 0.10.0
After the PR is agreed and merge of this PR one of the codeowner should:
- Create the release `v0.10.0` within GitHub (use the text for v0.10.0 from CHANGELOG.md as the release description)
- Create the branch `release-0.10.0` on the same commit which is tagged as v0.10.0
- Create a PR to change the version of the OAS YAML within main to `v0.11.0-wip`
Fixes #263 
The links which are containing `release-0.10.0` will get only valid when the PR is merged, and the release branch is created.
Please have a special view on the "Please …
=> Creation of release v0.10.0

CHANGELOG.md, README.md, code/API_definitions/qod-api.yaml
Updated CHANGELOG, README.md and version number in yaml file, tag the merge commit of the PR as v0.10.1.
The merge commit of this PR will be tagged as v0.10.1 (only then the links will get valid).
In addition made the links towards the YAML file independent of the release branches by pointing to the tags (as the release branches might be discontinued based on the discussion within Release Management)
Fixes #278 
To be merged after #277 is merged (information already included in CHANGELOG).
na
=> Create patch release v0.10.1

README.md, documentation/MeetingMinutes/README.md
Fixes the meeting-minute link to confluence.
Fixes #307
=> Update meeting-minute link in README.md

code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
* cleanup
Removes Terms of service and contact from the api.
Fixes #310 
```
release-note
- Removed TermsOfService and Contact from APIs since they are optional and did not provide useful information.
```
```
docs
```
=> Remove ToS and contact info

code/API_definitions/quality-on-demand.yaml
* correction
Correction within documentation. Removed reference and added note about Network Access Identifier in v0.11.0
Fixes #321
=> Removed unresolved reference within quality-on-demand.yaml

code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
* enhancement
This PR adds additional HTTP status codes to the QoD APIs.
- 429: Too Many Requests
Fixes #305
=> Add HTTP-429 for quality-on-demand

CODEOWNERS
=> Add jlurien as  CODEOWNER

code/API_definitions/quality-on-demand.yaml
* correction
Wrong info
Fixes #346
=> Fix duration info

README.md, documentation/MeetingMinutes/README.md
* correction
Correct wiki links after the migration (former short links are no longer working within the new wiki space).
Fixes # na
=> Patch wiki links

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
* correction
Updated "Authorization and authentication" section in all three API definitions
Fixes #361 
```
Updated "Authorization and authentication" section
```
=> 361 authorization and authentication section need to be aligned with icm 020 text

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
Prepare for the work on r2.1
Fixes # na
=> Resetting version numbers to wip after r1.3

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml, code/Test_definitions/qod-provisioning-createProvisioning.feature, code/Test_definitions/qod-provisioning-deleteProvisioning.feature, code/Test_definitions/qod-provisioning-getProvisioningById.feature, code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature, code/Test_definitions/qos-profiles-getQosProfile.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-deleteSession.feature, code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature, code/Test_definitions/quality-on-demand-getSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
Reset version numbers to wip following r2.1
Fixes #N/A
Merge this one next
```
release-note
- Reset version numbers to wip following r2.1
```
None
=> Reset version numbers to wip following r2.1

CHANGELOG.md, README.md, code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml, code/Test_definitions/README.md, code/Test_definitions/qod-provisioning-createProvisioning.feature, code/Test_definitions/qod-provisioning-deleteProvisioning.feature, code/Test_definitions/qod-provisioning-getProvisioningById.feature, code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature, code/Test_definitions/qod-provisioning-triggerProvisioning.feature, code/Test_definitions/qos-profiles-getQosProfile.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-deleteSession.feature, code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature, code/Test_definitions/quality-on-demand-getSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature, documentation/API_documentation/qod-provisioning-API-Readiness-Checklist.md, documentation/API_documentation/qos-profiles-API-Readiness-Checklist.md, documentation/API_documentation/quality-on-demand-API-Readiness-Checklist.md
* update the versions and server URLs in API and test definition files
* update the API readiness checklists, including adding the link to the test result statements issue
* add section for r2.2 to the changelog
* update README.md, including the changes for the new stage "Incubating"
Fixes #422 
Following PRs are added as changes between r2.1 and r2.2, and need all be merged before the release PR:
- #420
- #423 
- #424
```
release-note
```
```
docs
```
=> Release r2.2 for Spring25 m4 milestone

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml, code/Test_definitions/qod-provisioning-getProvisioningById.feature, code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature, code/Test_definitions/qod-provisioning-revokeProvisioning.feature, code/Test_definitions/qod-provisioning-triggerProvisioning.feature, code/Test_definitions/qos-profiles-getQosProfile.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-deleteSession.feature, code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature, code/Test_definitions/quality-on-demand-getSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
Prepare repository for work on Fall25
Fixes #428 
```
release-note
```
```
docs
```
=> Versions and server URLs set to wip

code/Test_definitions/qos-profiles-getQosProfile.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/qos-provisioning-createQosAssignment.feature, code/Test_definitions/qos-provisioning-getQosAssignmentByDevice.feature, code/Test_definitions/qos-provisioning-getQosAssignmentById.feature, code/Test_definitions/qos-provisioning-revokeQosAssignment.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-deleteSession.feature, code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature, code/Test_definitions/quality-on-demand-getSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
Fixes indentation, multiple blank line and trailing space errors in feature files for compliance with centralised linting rules
Fixes #
This PR does not fix all linting errors
```
release-note
- Fix indentation, multiple blank line and trailing space errors in feature files
```
None
=> Fix indentation, multiple blank line and trailing space errors in feature files

code/Test_definitions/qos-provisioning-getQosAssignmentByDevice.feature, code/Test_definitions/qos-provisioning-revokeQosAssignment.feature
Remove blank lines inadvertently added when fixing feature files
Fixes #
None
```
release-note
- Remove blank lines inadvertently added when fixing feature files
```
None
=> Remove blank lines inadvertently added when fixing feature files

code/API_definitions/qos-profiles.yaml, code/API_definitions/qos-provisioning.yaml, code/API_definitions/quality-on-demand.yaml
- Updates descriptions of properties of type=string and format=date-time
- Updates descriptions in ErrorModel
Fixes #483 
In ErrorModel I have kept the order that we had (status, code, message) even if in CAMARA_common.yaml is now (message, status, code) because all error responses examples show the previous order.
```
- Align some properties descriptions to latest guidelines
```
=> Alignment with Commonalities r3.3
