camaraproject/QualityOnDemand

documentation/API_documentation/QoD_API.md
After the content update for v0.8.0 with #71 here some editorial fixes within QoD_API.md, also to create a stable base for further updates/PRs:
* Reformated some tables as HTML tables (to get rid of the overlong source code lines which couldn't be reviewed)
* More consistent use of QoD vs QoS
* Consistent use of "QoS session resource" instead "QoS session"
* Consolidated mixed use of "mobile network operator" vs "communication service provider"
* Some further minor typos
Will close #58 
NOTE: this PR is not about correcting content issues (like error code etc), these should be raised as issues, especially if also the API definition YAML need to be changed
=> Editorial updates of documentation QoD_API.md

documentation/API_documentation/QoD_API.md
Small improvement for having a consistent use and spelling of "QoD API" and "QoS profiles" throughout the documentation.
=> Use the terms QoS profiles and QoD API consistently

code/API_definitions/qod-api.yaml, documentation/API_documentation/QoD_API.md
=> Update from notificationsUri to notificationsUrl

code/API_definitions/qod-api.yaml
=> Fixed couple of typos

CHANGELOG.md, code/API_definitions/qod-api.yaml
Will close #105
Please review this release proposal:
- that everything is included that you expected in v0.8.1
- that the CHANGELOG.md reflects the changes done since v0.8.0
After review and merge of the PR
a) the merge commit of the PR will get tagged as v0.8.1 and get the release branch v0.8.1
b) the text for v0.8.1 in CHANGELOG.md will get the release description of v0.8.1 in the Github release
=> CHANGELOG.md update for v0.8.1 release

code/API_definitions/qod-api.yaml
As agreed in the discussion in Commonalities (https://github.com/camaraproject/WorkingGroups/issues/151), we should adopt the new agreement to refer to the common ErrorInfo schema for every error.
=> chore: refer-to-common-ErrorInfo-schema

code/API_definitions/qod-api.yaml, documentation/API_documentation/QoD_API.md
- Applied lowerCamelCase for property names, UpperCamelCase for schema names
- Updated API_documentation as well. This is a redundant effort that hopefully we don't have to maintain in the future, as being discussed in https://github.com/camaraproject/WorkingGroups/issues/164
- In a separate PR we should enhance descriptions, once Glossary definitions are consolidated.
=> Rename properties to new terms

code/API_definitions/qod-api.yaml, documentation/API_documentation/QoD_API.md
This PR introduces the new schema `DeviceIpv4Addr`, which is used for the `ipv4Address` property of the `Device` object. The `DeviceIpv4Addr` object allows the `device` to be identified by a combination of its public IPv4 address (`publicAddress`) and at least one of either its public port (`publicPort`) or private (device local) IPv4 address (`privateAddress`).
This modified schema is required to support the scenario where it is desired to identify the `device` by its private (local) IPv4 address, as this alone is generally insufficient to identify the device, and the public (NATed) IPv4 address must also be provided.
Fixes #34 : **Resolving ueAddr ambiguity when it is the UE private address**
- For NAT64 scenarios, it has been confirmed that the …
=> Updated method for identifying devices by IPv4 address

code/API_definitions/qod-api.yaml
* correction
Applicable values for QosStatus in the context of an event are limited to `AVAILABLE` and `UNAVAILABLE`. As model was previously reused between the event and the regular SessionInfo, `REQUESTED` was also allowed in events.
Raised as comment in PR #155, but not solved there. 
```
- Added new model `EventQosStatus`
```
=> Correction: Split QosStatus enum

code/API_definitions/qod-api.yaml
Fix ability to send QosStatusChangedEvent from client side (Telco) to the server side of /notifications (QoS API Consumer) for those who use strongly typed Languages.
As QosStatusChangedEvent extends Event we can now send it as payload
Fixes #174
~~BREAKING CHANGE: Remove EventNotification to embed Event as notification payload~~ (reverted, see [bbe5812](https://github.com/camaraproject/QualityOnDemand/pull/177/commits/bbe5812db50f1b6bd0fa3f6b58bade2213a1fd70))
This specification replaces multiple inheritance schemes with single inheritance. This way the generator will stop to generate anonymous XXXAllOf.java classes which are not useful at all.
```yaml
ClassA:
allOf:
- $ref: ClassB
- type: object
properties:
prop1:
```   
That says ClassA inherit from ClassB and …
=> fix(openapi): Add inheritance beetween Event and QosStatusChangedEvent

.github/workflows/swagger-editor-validator.yml
* tests
This will run the swagger editor validator github action on all pull requests to validate the correctness of the openAPI content.
This is the first PR to address #158
Fixes #
This is a fairly simple test that will validate the correctness of the OpenAPI file.  Additional linters will be added to check against commonalities.
```
Added swagger editor validator github action for all pull requests
```
```
docs
```
=> Adding swagger editor validator github action

CHANGELOG.md, README.md
documentation
subproject management
Update README and CHANGELOG, adding Redoc and Swagger links for v0.9.0 which allow to view the API definition and documentation in a more visual and friendly way.
Fixes #199 
Same change as in CHANGELOG will be applied (manually) to the v0.9.0 release definition in Github as soon as the PR is merged.
=> Update of CHANGELOG and README with user friendly doc links

code/API_definitions/qod-api.yaml
* enhancement 
There is no expected behaviour for an malformed Session-Id in the GET- & DELETE-request.
This PR shell add a Bad Request (HTTP 400) for the GET & DELETE /sessions/{sessionId} - endpoint.
Fixes #209
=> add 400 - Bad Request for invalid session ID in GET & DELETE /sessions/{sessionId}

code/API_definitions/qod-api.yaml
* correction
Operation tags should be defined in a top-level `tags` element.
Fixes #223
Description field is rendered by Swagger this way:
```
Global tags element added
```
=> Adding global tags element 

code/API_definitions/qod-api.yaml
enhancement/feature
Extend the duration of an active session.
Fixes #220 
```
release-note
```
```
docs
```
=> Extend session duration

code/API_definitions/qod-api.yaml
Align QoD event notification with recently approved guidelines adhering to CloudEvents specification
Fixes #221 
```
- Notification event changed to comply with CloudEvents specification
```
=> Align event notification with CloudEvents spec

code/API_definitions/qod-api.yaml
* IPv6 address in device changed to SingleIpv6Adress. IPv6 address in ApplicationServer is not changed
* Patterns for single IPv4 and IPv6 adresses, used in device model, substituted for the standards ipv4 and ipv6 formats defined in JSON-schema
Fixes #230 
```
* Single IP addresses in Device model specified with standard formats instead of patterns
```
=> Single IP addresses in Device model specified with standard formats instead of patterns

CHANGELOG.md, README.md, code/API_definitions/qod-api.yaml
The merge of this PR will be the target commit for the first release candidate of v0.10.0, getting the tag `v0.10.0-rc`
Fixes #235 
Currently draft PR, as the final information about the PRs included in the release candidate are not yet available.
NA
=> Creation of release candicate v0.10.0-rc

code/API_definitions/qod-api.yaml
- Added new example for DurationOutOfRangeForQoSProfile
- Version set to 0.10.0-wip
Fixes #247
=> New example for DurationOutOfRangeForQoSProfile

code/API_definitions/qod-api.yaml
Add a note to maxDuration parameter that the value shouldn't exceed the current limitation within sessionInfo of 86400 seconds
This is a temporary measure for #249 but won't fix it. See comment within the issue.
```
Added a note to maxDuration parameter within qosProfile about the limit of 86400 seconds
```
=> Added a note to maxDuration parameter within qosProfile about the limit of 86400 seconds

code/API_definitions/qod-api.yaml
* correction
Adding clarification that notification will be sent for all changes of qosStatus and what happens when qosStatus change from AVAILABLE to UNAVAILABLE
Fixes #241 and #254
As notification should be sent in all QosStatus changes, there was the need to add the StatusInfo "DELETE_REQUESTED". 
```
Clarified in documentation that notifications will be sent for all changes of QosStatus, even if initiated by the client.
Clarified in documentation that the QoS session resource what will happen when qosStatus changes from 'AVAILABLE' to 'UNAVAILABLE' due to 'NETWORK_TERMINATED'
```
=> Added clarification of notifications to be sent and added StatusInfo "DELETE_REQUESTED" to addres #241

.openapirc.yml, CHANGELOG.md, README.md, code/API_definitions/qod-api.yaml
Create the second release candidate of v0.10.0-rc2:
* Update CHANGELOG.md with changes since v0.10.0-rc
* Update README.md with links to v0.10.0-rc2
Fixes #260 
- This PR is meant to be merged after #258.
- The links within CHANGELOG.md and README.md are getting valid after the tag v0.10.0-rc2 is created (pointing to merge request of this PR).
- The new text within CHANGELOG.md will be copied into the description of the Github pre-release v0.10.0-rc2.
=> Second release candidate of v0.10.0

code/API_definitions/qod-api.yaml
* bug
- Improve the documentation of "Extend the duration of an active session".
- Improve the datatype "SessionInfo" to remove the maximum limit of duration.
Fixes https://github.com/camaraproject/QualityOnDemand/issues/272
```
release-note
```
```
docs
```
=> Fix maximum duration in session info and improve documentation

code/API_definitions/qod-api.yaml
* correction
- Add x-correlator to all requests and responses
- Added some missing descriptions to silent linting warnings
- Remove weird use of allOf for example
Fixes #271
Fixes #282
```
- Added x-correlator header to requests and responses
```
=> Add X-Correlator and other fixes

MAINTAINERS.MD
Collected the GitHub names to be able to invite the right people into the quality-on-demand_maintainer team.
As part of the CAMARA organisation improvements we are creating groups for the maintainers and codeowners of all sub projects. As part of this, we have collected the GitHub names of the sub project maintainers to invite the right people.
Fixes #
```
release-note
```
```
docs
```
=> Update MAINTAINERS.MD - Added GitHub names

code/API_definitions/quality-on-demand.yaml
* correction
Alignment with Commonalities about + prefix for international E.164 phoneNumbers 
Fixes #298
=> Make + prefix mandatory for phoneNumber

code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
Clarification and consolidation of changes affecting management of session duration.
- For creation, duration is made required. Maximum and default are deprecated, relying on the QoS Profile API for any limit. Implementations can grant the requested duration or set a different value in the response.
- maxDuration in QoS Profiles is assumed to be the absolute maximum duration including any extensions. That is, extensions can extend the current session duration to the maximumDuration but no longer.
Session info changes:
- dates are formatted as string, date-format.
- startedAt and expiredAt are both optional and not expected to be returned when qosStatus is "REQUESTED".
- duration is the overall session duration, including any extension. It should be the interval …
=> Consolidation of changes related to session duration

code/API_definitions/quality-on-demand.yaml
* correction
* Remove unused `messages` object in the `SessionInfo` schema
Fixes #309
As discussed in today's [call](https://wiki.camaraproject.org/display/CAM/2024-06-28+Quality+on+Demand+-+Meeting+Minutes) 
```
Removed unused `messages` object in the `SessionInfo` schema
```
=> Remove unused messages object in SessionInfo schema

code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
ICM have updated the mandatory AuthZ/AuthN template wording between release 0.1.0 and release 0.2.0 (currently a release candidate)
None
Should be a draft PR until ICM release is finalised
```
release-note
- Update ICM AuthZ/AuthN template to Release 0.2.0 wording
```
None
=> Update ICM AuthZ/AuthN Template to Release 0.2.0 wording

code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
* correction
* Add documentation about "Handling of device information" within the API description. Made device parameter optional within createSession
* Aligned Device object and info object with Commonalities
* Updated errorMessages according to Commonalities.
* Added 422, removed 501 (as createSession is not optional within the API, and then 501 is not any more used)
* Replaced 400 error response examples with Generic400 from Commonalities, introduced specific error code QUALITY_ON_DEMAND.DURATION_OUT_OF_RANGE
Fixes #313
Fixes #315 
Fixes #316 
~~Intentionally only done for quality-on-demand to reduce potential merge conflicts.~~
Done for both APIs quality-on-demand and qos-profiles.
```
Made device object optional within …
```
=> Align quality-on-demand with Commonalties regarding optional device object and error messages

code/API_definitions/quality-on-demand.yaml
Aligns on Commonalities' updated subscription model.
Fixes #332
=> Align on Commonalities' subscription-model by using `sink` and `sinkCredentials`

code/API_definitions/quality-on-demand.yaml
Adds a new endpoint to return a list of sessions for a given device, thus it will be possible to look for sessions for a given device without knowing the assigned sessionId.
Fixes #101 
Deprecates PR #228
I have made device required in the input, to be aligned with the rest of the API in this PR. There is a separate issue #313 to decide on the alignment of the API with the guidelines regarding device identification and making it optional in the request body.
```
* New operation retrieveSessions to get a list of sessions for a given device
```
=> List sessions endpoint for quality-on-demand

code/API_definitions/qod-provisioning.yaml, code/API_definitions/quality-on-demand.yaml
* correction
Resolve "TBC" reference leftover, see #333 
Fixes #333
Wording to be discussed/approved in QoD call today.
Can be merged either before or after the Release PR (there would be no need to mention in r1.1 release notes as it is a correction of API split).
=> Fix of reference to qos-profiles API in quality-on-demand.yaml

CHANGELOG.md, README.md, code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml, documentation/API_documentation/Notifications.md, documentation/API_documentation/qod-provisioning-API-Readiness-Checklist.md, documentation/API_documentation/qos-profiles-API-Readiness-Checklist.md, documentation/API_documentation/quality-on-demand-API-Readiness-Checklist.md
Prepare the release r1.1:
Update - additional fixes
- Aligned sink description between quality-on-demand and qod-provisioning to address #338 
Fixes #334 #338
=> Prepare release r1.1

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
* bug
- Fix example which was not compliant with new schema
- Main version set to wip again
Fixes #343 
To be considered for r1.2 (RC2)
```
- Fix RETRIEVE_SESSIONS_EXAMPLE
```
=> Quality on Demand: Fix RETRIEVE_SESSIONS_EXAMPLE

code/API_definitions/qos-profiles.yaml
* correction
Updates the endpoint names to include a verb.
Adds security scope to /retrieve-qos-profiles
Updates security scope on /retrieve-qos-profiles/{name}
Fixes #345
Should `/retrieve-qos-profiles/{name}` be singular `/retrieve-qos-profile/{name}` since it only returns a single qos-profile.
```
release-note
Update qos-profile endpoint names to align with commonalites.  Updates the endpoint names to include a verb.
`/qos-profiles` is now `/retrieve-qos-profiles` and `/qos-profiles/{name}` is now `/retrieve-qos-profiles/{name}`
```
```
docs
```
=> Updating names qos-profile of endpoints

code/API_definitions/quality-on-demand.yaml
* correction
Clarifies the undefined behaviour if API consumer tries to extend a session which is state REQUESTED or UNAVAILABLE as discussed in #351 
Fixes #351
=> Add new error schema to extendDuration: SessionStateInConflict409 with QUALITY_ON_DEMAND.SESSION_EXTENSION_NOT_ALLOWED 

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
Fixes issues Add explanation on why there is a "POST /retrieve-sessions" instead of GET #359
Clarifies why a POST call is used of a GET to retrieve data from the QoD APIs.
Fixes #359 
```
Added notes to retrieve POST calls to explain why these are a POST instead of a GET.
```
```
docs
```
=> Updating the notes for the retrieve POST calls

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
Provides guidance on using the QoD APIs in multi-SIM scenarios
Fixes #376 
This guidance will need to be updated when Commonalities Issue [#302](https://github.com/camaraproject/Commonalities/issues/302) is resolved
```
release-note
- Add guidance for multi-SIM scenarios
```
None
=> Add guidance for multi-SIM scenarios

CHANGELOG.md, README.md, code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml, code/Test_definitions/qod-provisioning-createProvisioning.feature, code/Test_definitions/qod-provisioning-deleteProvisioning.feature, code/Test_definitions/qod-provisioning-getProvisioningById.feature, code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature, code/Test_definitions/qos-profiles-getQosProfile.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-deleteSession.feature, code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature, code/Test_definitions/quality-on-demand-getSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature, documentation/API_documentation/qod-provisioning-API-Readiness-Checklist.md, documentation/API_documentation/qos-profiles-API-Readiness-Checklist.md, documentation/API_documentation/quality-on-demand-API-Readiness-Checklist.md
Update of README and changelog for patch release r1.3
Updating release numbers and API versions across all files
Replacing links to main branch with release specific links (closing the remaining issue from the patch release scope in #
Fixes #381 
Fixes #363
Create temporarily created branch `r1.3` from main to be able to test the links. That branch will need be deleted before the release tag can be created.
```
na
```
=> Patch release r1.3

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml, code/Test_definitions/qod-provisioning-createProvisioning.feature, code/Test_definitions/qod-provisioning-deleteProvisioning.feature, code/Test_definitions/qod-provisioning-getProvisioningById.feature, code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature, code/Test_definitions/qos-profiles-getQosProfile.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-deleteSession.feature, code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature, code/Test_definitions/quality-on-demand-getSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
* correction
Commonalities [0.5.0-alpha.1](https://github.com/camaraproject/Commonalities/releases/tag/r2.1) updates the error response codes associated with device handling.
This PR:
- Updates the error response codes and schemas as necessary in the OAS definitions
- Updates the test cases as necessary
- Removes the `403 INVALID_TOKEN_CONTEXT` error from the OAS definitions
- Removes all 5XX errors as these no longer require to be explicitly documented
- Updates `info.description` text on device object handling in each OAS definition
- Ensures `date-time` examples are enclosed by quotation marks
Fixes #390, #392, #389, #394
None
```
release-note
- Updates the error response codes and schemas as necessary in the OAS definitions
- Updates the test cases as necessary
- Removes the `403 …
```
=> Update error responses and test cases to comply with Commonalities 0.5.0

code/API_definitions/qos-profiles.yaml
Expands on the intro to the QoS Profile to include it's intended use.
Fixes #393 
@tanjadegroot this should address your feedback in https://github.com/camaraproject/QualityOnDemand/pull/383#issuecomment-2551470240. Please review.  
```
release-note
Updated top level description of QoS Profile.
```
```
docs
```
=> Updating the intro to the QoS Profile.

code/API_definitions/qos-profiles.yaml
Add L4S/Diffserv support to Qos Profile
Fixes #173 
```
release-note
```
```
docs
```
=> Add L4S/DSCP support to QoS Profile

code/Test_definitions/README.md, code/Test_definitions/qod-provisioning-createProvisioning.feature, code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
* tests
Error scenarios for device management are designed in a new artifact in Commonalities, that can be reused. This deprecates previous scenarios testing the same aspects.
README has been updated, removing some technical debt that has been resolved
Fixes #398
To be updated also with outcome of #399 
```
Error handling for device management updated to latest guidelines
```
=> Use common artifact for device test scenarios

code/API_definitions/qos-profiles.yaml
Text needs to be adapted as NOT providing a device identifier (either via token or explicit request body parameter) is NOT an error.
- Updates text, indicating that providing both a 3-legged token and explicit device identifier is an error, but providing neither is not
- Remove error `422 MISSING_IDENTIFIER` as this is not a valid error for either endpoint
Fixes #399 
`422 IDENTIFIER_MISMATCH` left in as explicit `device` object may contain mismatched identifiers
`422 SERVICE_NOT_APPLICABLE` left in as some implementations may prefer to indicate that the service is just not available for a specific device rather than saying no profiles are currently available for that device
Test cases not yet updated
```
release-note
- Updates text, indicating that providing both a …
```
=> Adapt text on identifying devices from the access token for qos-profiles.yaml

code/API_definitions/qod-provisioning.yaml, code/API_definitions/quality-on-demand.yaml
* correction
Commonalities v0.5.0 will require notification sink format to be `uri` rather than `url`. This ensures RFC 3986 compliance. See [here](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#instance-based-implicit-subscription).
Fixes #413 
None
```
release-note
- Change notification sink format from url to uri
```
None
=> Change notification sink format from url to uri

code/API_definitions/qod-provisioning.yaml, code/Test_definitions/qod-provisioning-getProvisioningById.feature, code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature, code/Test_definitions/qod-provisioning-revokeProvisioning.feature, code/Test_definitions/qod-provisioning-triggerProvisioning.feature
Being "provisioning" a process and not a "resource", it does not sound well to create or delete a provisioning, but to trigger the process or to revert or revoke the assignments done by a previous provisioning process.
Adresses part of #415 but will not close it
Only some descriptions and operationIds have been adjusted for this Meta, as there is no a clear alternative for the names of the resources used in path, scopes, etc, and this change is critical to be done for this Meta-release without a thoughtful discussion.
As this is still an initial version of the API we will work further on those aspects towards a future meta-release, taking feedback from early integrations.
```
- operationIds renamed and some descriptions changed
```
```
docs
```
=> Update wording in the qod-provisioning API

CHANGELOG.md, README.md
This pull request migrates swagger editor links to use the CAMARA project's dedicated swagger-ui instance for better reliability (original links to swagger.io were broken).
**Changes:**
- Replaced `https://editor.swagger.io/` with `https://camaraproject.github.io/swagger-ui/`
- Replaced `https://editor-next.swagger.io/` with `https://camaraproject.github.io/swagger-ui/`
- All API specification URLs remain unchanged - only the swagger editor host is updated
**Benefits:**
- Consistent CAMARA experience
- Centralized swagger-ui configuration
- Maintained compatibility with existing specification URLs
**Files modified:**  README.md CHANGELOG.md
**Links updated:** 23
🔧 **Generated via project-admin workflow**  
Triggered by hdamker
---
*This is an automated administrative update.*
=> chore: migrate swagger editor links to CAMARA swagger-ui

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml
Added mandatory text "Additional CAMARA error responses" to all three APIs
Removed historic "Further info and support" section from qos-profiles and quality-on-demand
Fixes #451 
```
release-note
```
```
docs
```
=> Add error response documentation in oas definitions

code/API_definitions/qod-provisioning.yaml, code/API_definitions/qos-profiles.yaml, code/API_definitions/quality-on-demand.yaml, code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature, code/Test_definitions/qod-provisioning-triggerProvisioning.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
* correction
Commonalities has removed the `IDENTIFIER_MISMATCH` error for Fall25. Instead, a device identifier should not normally be included in responses. It should only be included to disambiguate the identity of the device when:
- the endpoint is being accessed using a 2-legged access token; and
- the endpoint allows for a device identifier to be provided in the request; and
- the API consumer has included multiple device identifiers
The response then includes the device identifier that was used by the implementation
This PR:
- Updates documentation in each OAS
- Adds relevant example both for when device disambiguation is required, and when it is not required
- Uses `DeviceResponse` object to limit device identifiers in responses to exactly one
- Removes the IDENTIFIER_MISMATCH …
=> Update OAS definitions to remove IDENTIFIER_MISMATCH error code

code/API_definitions/qod-provisioning.yaml, code/Test_definitions/qod-provisioning-getProvisioningById.feature, code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature, code/Test_definitions/qod-provisioning-revokeProvisioning.feature, code/Test_definitions/qod-provisioning-triggerProvisioning.feature
* cleanup
The API specification has undergone several significant improvements to address terminology issues and enhance clarity:
* Title changed from "QoD Provisioning API" to "QoS Provisioning", updating all related tags, scopes, urls, eventTypes etc
* Better clarify that "provisioning" is a process, not a thing
* Paths changed: 
-  `/device-qos` to `/qos-assignments`
- `/retrieve-device-qos` to `/retrieve-qos-assignment`
* Updated operation IDs to be more descriptive (e.g., triggerQosProvisioning)
* Improved endpoint summaries and descriptions
Fixes #415 
- **Filename has not been renamed so changes are easier to detect and review, but if we agree on the new name we should later rename it**
```
- API renamed to QoS Provisioning
- URLs and paths changed
- Descriptions …
```
=> Refine terminology in qos-provisioning API

code/API_definitions/qos-profiles.yaml, code/API_definitions/qos-provisioning.yaml, code/API_definitions/quality-on-demand.yaml, code/Test_definitions/qos-profiles-getQosProfile.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/qos-provisioning-createQosAssignment.feature, code/Test_definitions/qos-provisioning-getQosAssignmentByDevice.feature, code/Test_definitions/qos-provisioning-getQosAssignmentById.feature, code/Test_definitions/qos-provisioning-revokeQosAssignment.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-deleteSession.feature, code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature, code/Test_definitions/quality-on-demand-getSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
* repository management
Setting the version in API and test definitions back to wip after r3.1 to clearly indicate that any change done between r3.1 and r3.2 does not belong to neither of the releases. 
That will allow to address open issues with PRs without taking care of the version field.
Fixes # none (repository management)
Good practice as done in the past (see for example https://github.com/camaraproject/QualityOnDemand/pull/421)
=> Reset versions in API and test definitions back to wip after r3.1

code/Test_definitions/qos-profiles-getQosProfile.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/qos-provisioning-getQosAssignmentByDevice.feature, code/Test_definitions/qos-provisioning-getQosAssignmentById.feature, code/Test_definitions/qos-provisioning-revokeQosAssignment.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-deleteSession.feature, code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature, code/Test_definitions/quality-on-demand-getSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
* bug
* correction
* tests
Fix minor issues and typos in test plan for M4
Fixes #503
=> Fix minor issues and typos in test plan

CHANGELOG.md, README.md, code/API_definitions/qos-profiles.yaml, code/API_definitions/qos-provisioning.yaml, code/API_definitions/quality-on-demand.yaml, code/Test_definitions/qos-profiles-getQosProfile.feature, code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature, code/Test_definitions/qos-provisioning-createQosAssignment.feature, code/Test_definitions/qos-provisioning-getQosAssignmentByDevice.feature, code/Test_definitions/qos-provisioning-getQosAssignmentById.feature, code/Test_definitions/qos-provisioning-revokeQosAssignment.feature, code/Test_definitions/quality-on-demand-createSession.feature, code/Test_definitions/quality-on-demand-deleteSession.feature, code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature, code/Test_definitions/quality-on-demand-getSession.feature, code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature, documentation/API_documentation/qos-profiles-API-Readiness-Checklist.md, documentation/API_documentation/qos-provisioning-API-Readiness-Checklist.md, documentation/API_documentation/quality-on-demand-API-Readiness-Checklist.md
- Set API versions
- quality-on-demand v1.1.0
- qos-profiles v1.1.0
- qos-provisioning v0.3.0
- Update test defininitions
- Update changelog
- Update readme
- Update readiness checklist files
Fixes #494
=> Release r3.2 (M4 Fall25)
